import { College, Question } from "@/types";

export const colleges: College[] = [
  {
    id: "1",
    name: "IIT Bombay",
    location: "Mumbai, Maharashtra",
    fees: 250000,
    rating: 4.8,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    placements: { avgPackage: 2100000, topRecruiter: "Google" },
    overview: "IIT Bombay is one of India's premier engineering institutions, known for cutting-edge research and top placements.",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=600&q=80",
  },
  {
    id: "2",
    name: "IIT Delhi",
    location: "New Delhi, Delhi",
    fees: 240000,
    rating: 4.7,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    placements: { avgPackage: 2000000, topRecruiter: "Microsoft" },
    overview: "IIT Delhi is a world-class institution located in the capital, with strong industry connections.",
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&q=80",
  },
  {
    id: "3",
    name: "NIT Trichy",
    location: "Tiruchirappalli, Tamil Nadu",
    fees: 150000,
    rating: 4.5,
    courses: ["B.Tech", "M.Tech", "MCA"],
    placements: { avgPackage: 1200000, topRecruiter: "Amazon" },
    overview: "NIT Trichy is one of the top NITs in India, known for excellent academics and placements.",
    image: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=600&q=80",
  },
  {
    id: "4",
    name: "BITS Pilani",
    location: "Pilani, Rajasthan",
    fees: 520000,
    rating: 4.6,
    courses: ["B.Tech", "B.Pharm", "MBA", "M.Tech"],
    placements: { avgPackage: 1800000, topRecruiter: "Qualcomm" },
    overview: "BITS Pilani is a premier private institution known for its practice school and strong alumni network.",
    image: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=600&q=80",
  },
  {
    id: "5",
    name: "VIT Vellore",
    location: "Vellore, Tamil Nadu",
    fees: 380000,
    rating: 4.1,
    courses: ["B.Tech", "M.Tech", "MBA", "MCA"],
    placements: { avgPackage: 900000, topRecruiter: "Wipro" },
    overview: "VIT Vellore is one of India's largest private universities with strong industry partnerships.",
    image: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=600&q=80",
  },
  {
    id: "6",
    name: "IIT Madras",
    location: "Chennai, Tamil Nadu",
    fees: 245000,
    rating: 4.9,
    courses: ["B.Tech", "M.Tech", "PhD", "MBA"],
    placements: { avgPackage: 2200000, topRecruiter: "Apple" },
    overview: "IIT Madras is India's top-ranked engineering college with a beautiful campus and world-class faculty.",
    image: "https://images.unsplash.com/photo-1576495199011-eb94736d05d6?w=600&q=80",
  },
  {
    id: "7",
    name: "DTU Delhi",
    location: "New Delhi, Delhi",
    fees: 170000,
    rating: 4.2,
    courses: ["B.Tech", "M.Tech", "MBA"],
    placements: { avgPackage: 1100000, topRecruiter: "Samsung" },
    overview: "Delhi Technological University is a top state university known for engineering excellence.",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600&q=80",
  },
  {
    id: "8",
    name: "IIIT Hyderabad",
    location: "Hyderabad, Telangana",
    fees: 320000,
    rating: 4.4,
    courses: ["B.Tech", "M.Tech", "PhD"],
    placements: { avgPackage: 1600000, topRecruiter: "Meta" },
    overview: "IIIT Hyderabad is a research-focused institute specializing in computer science and AI.",
    image: "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=600&q=80",
  },
];

export const questions: Question[] = [
  {
    id: "q1",
    collegeId: "1",
    question: "What is the hostel life like at IIT Bombay?",
    author: "Rahul M.",
    createdAt: "2024-03-01",
    answers: [
      { id: "a1", text: "Hostel life is amazing! Great facilities and a vibrant student community.", author: "Priya S.", createdAt: "2024-03-02" },
    ],
  },
  {
    id: "q2",
    collegeId: "1",
    question: "How are the placements for CSE branch?",
    author: "Ankit R.",
    createdAt: "2024-03-05",
    answers: [],
  },
  {
    id: "q3",
    collegeId: "3",
    question: "Is NIT Trichy good for mechanical engineering?",
    author: "Sneha K.",
    createdAt: "2024-02-20",
    answers: [
      { id: "a2", text: "Yes, mechanical is one of the strongest departments here.", author: "Kiran V.", createdAt: "2024-02-21" },
    ]
  }
]